// *** WARNING: this file was generated by the Pulumi Kubernetes Istio codegen tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// Import versions:
import * as v1 from './v1';

// Export sub-modules
export { v1,  };
