// *** WARNING: this file was generated by the Pulumi Kubernetes Istio codegen tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// Export kinds:
export * from './destination-rule';
export * from './envoy-filter';
export * from './gateway';
export * from './service-entry';
export * from './sidecar';
export * from './virtual-service';
