// *** WARNING: this file was generated by the Pulumi Kubernetes Istio codegen tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import { CustomResourceOptions } from '@pulumi/pulumi';
import * as k8s from '@pulumi/kubernetes';

import { input } from '../../types';

export class Handler extends k8s.apiextensions.CustomResource {
  constructor(name: string, args: input.policy.v1beta1.HandlerArgs, opts?: CustomResourceOptions) {
    const inputs: k8s.apiextensions.CustomResourceArgs = {
      apiVersion: 'policy.istio.io/v1beta1',
      kind: 'Handler',
      ...args,
    };

    super(name, inputs, opts);
  }
}
