// *** WARNING: this file was generated by the Pulumi Kubernetes Istio codegen tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import { CustomResource, CustomResourceOptions, Inputs, Input, ID, Output } from '@pulumi/pulumi';
import { types } from '@pulumi/kubernetes';

import { input, output } from '../../types';


export class Rule extends CustomResource {
    /** @internal */
    private static readonly __pulumiType = 'kubernetes:security.istio.io/v1beta1:Rule';

    /**
     * Standard object metadata. More info:
     * https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
     */
    public readonly metadata: Output<types.output.meta.v1.ObjectMeta>;

    /**
     * Spec holds information about the request being evaluated
     */
    public readonly spec: Output<output.security.v1beta1.Rule>;

    public static get(name: string, id: Input<ID>, opts: CustomResourceOptions = {}): Rule {
        return new Rule(name, undefined, { ...opts, id });
    }

    /**
     * Returns true if the given object is an instance of DestinationRule.
     * This is designed to work even when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Rule {
        return obj != null && obj['__pulumiType'] === Rule.__pulumiType;
    }

    /**
     * Create a security.v1beta1.Rule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    // @TODO: Generate input types for args
    constructor(name: string, args: { metadata: types.input.meta.v1.ObjectMeta, spec: input.security.v1beta1.Rule }, opts: CustomResourceOptions = {}) {
        const inputs: Inputs = {
            apiVersion: 'security.istio.io/v1beta1',
            kind: 'Rule',
            metadata: args.metadata,
            spec: args.spec,
        };

        //if (!opts.version) {
        //    opts.version = getVersion();
        //}

        super(Rule.__pulumiType, name, inputs, opts);
    }
}